openapi: 3.0.0
info:
  title: Saas Training API
  description: API documentation for Saas Training
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
tags:
  - name: User Authentication
    description: Endpoints for user login and registration
  - name: Payments
    description: Endpoints for creating and managing payments
  - name: Subscriptions
    description: Endpoints for managing user subscriptions
  - name: AI Prompt Usage
    description: Endpoints for tracking AI prompt usage
  - name: Users
    description: Endpoints for user management
  - name: Subscription Plans
    description: Endpoints for managing subscription plans
  - name: API Test
    description: Endpoints for testing API functionality
components:
  parameters:
    x-access-token:
      in: header
      name: x-access-token
      required: true
      schema:
        type: string
      example: ${X_ACCESS_TOKEN}
security:
  - x-access-token: []
paths:
  # User Authentication
  /login:
    post:
      tags: ['User Authentication']
      summary: Login Pengguna
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              example:
                email: admin@solusikonsep.co.id
                password: u6{gHNaa
      responses:
        '200':
          description: Token akses berhasil dibuat
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string

  /register:
    post:
      tags: ['User Authentication']
      summary: Daftar Pengguna
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              example:
                name: User 01
                email: user01@solusikonsep.co.id
                password: u6{gHNaa
      responses:
        '200':
          description: Pengguna berhasil didaftarkan
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
                  created_at:
                    type: string
                    format: date-time

  # Payments
  /payments:
    post:
      tags: ['Payments']
      summary: Create Payments
      parameters:
        - $ref: '#/components/parameters/x-access-token'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                payment_status:
                  type: string
                payment_type:
                  type: string
              example:
                amount: 100000
                payment_status: pending
                payment_type: qris
      responses:
        '200':
          description: Pembayaran berhasil dibuat

  /payments/history:
    get:
      tags: ['Payments']
      summary: Get All Payments
      parameters:
        - $ref: '#/components/parameters/x-access-token'
      responses:
        '200':
          description: Daftar semua pembayaran

  /payments/notification:
    post:
      tags: ['Payments']
      summary: Payment Callback
      parameters:
        - $ref: '#/components/parameters/x-access-token'
      responses:
        '200':
          description: Callback notifikasi pembayaran

  # Subscriptions
  /user-subscriptions:
    get:
      tags: ['Subscriptions']
      summary: Get User Subscriptions
      parameters:
        - $ref: '#/components/parameters/x-access-token'
      responses:
        '200':
          description: Daftar langganan pengguna
    post:
      tags: ['Subscriptions']
      summary: Create User Subscriptions
      parameters:
        - $ref: '#/components/parameters/x-access-token'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                plan_id:
                  type: integer
                start_date:
                  type: string
                  format: date
                end_date:
                  type: string
                  format: date
                status:
                  type: string
              example:
                plan_id: 1
                start_date: 2025-01-01
                end_date: 2025-02-01
                status: active
      responses:
        '200':
          description: Langganan pengguna berhasil dibuat

  /user-subscriptions/{id}:
    put:
      tags: ['Subscriptions']
      summary: Update User Subscriptions
      parameters:
        - $ref: '#/components/parameters/x-access-token'
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                plan_id:
                  type: integer
                start_date:
                  type: string
                  format: date
                end_date:
                  type: string
                  format: date
                status:
                  type: string
              example:
                user_id: 1
                plan_id: 2
                start_date: 2025-01-31
                end_date: 2025-02-24
                status: active
      responses:
        '200':
          description: Langganan pengguna berhasil diperbarui
    delete:
      tags: ['Subscriptions']
      summary: Delete User Subscriptions
      parameters:
        - $ref: '#/components/parameters/x-access-token'
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Langganan pengguna berhasil dihapus

  # AI Prompt Usage
  /ai-prompt-usage:
    post:
      tags: ['AI Prompt Usage']
      summary: Create AI Prompt Usage
      parameters:
        - $ref: '#/components/parameters/x-access-token'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt_text:
                  type: string
              example:
                prompt_text: 00 | Generate a summary for the latest news article.
      responses:
        '200':
          description: Penggunaan prompt AI berhasil dibuat
    get:
      tags: ['AI Prompt Usage']
      summary: Get AI Prompt Usages
      parameters:
        - $ref: '#/components/parameters/x-access-token'
      responses:
        '200':
          description: Daftar penggunaan prompt AI

  # Users
  /users:
    post:
      tags: ['Users']
      summary: Create User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              example:
                name: User 01
                email: user01@example.com
                password: password123
      responses:
        '200':
          description: User successfully created
    get:
      tags: ['Users']
      summary: Get Users
      responses:
        '200':
          description: List of users

  /users/{id}:
    get:
      tags: ['Users']
      summary: Get User by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User details
    put:
      tags: ['Users']
      summary: Update User
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              example:
                name: Updated User
                email: updateduser@example.com
                password: newpassword123
      responses:
        '200':
          description: User successfully updated
    delete:
      tags: ['Users']
      summary: Delete User
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User successfully deleted

  # Subscription Plans
  /subscription-plans:
    post:
      tags: ['Subscription Plans']
      summary: Create Subscription Plan
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                duration:
                  type: integer
              example:
                name: Basic Plan
                price: 9.99
                duration: 30
      responses:
        '200':
          description: Subscription plan successfully created
    get:
      tags: ['Subscription Plans']
      summary: Get Subscription Plans
      responses:
        '200':
          description: List of subscription plans

  /subscription-plans/{id}:
    put:
      tags: ['Subscription Plans']
      summary: Update Subscription Plan
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                duration:
                  type: integer
              example:
                name: Updated Plan
                price: 19.99
                duration: 60
      responses:
        '200':
          description: Subscription plan successfully updated
    delete:
      tags: ['Subscription Plans']
      summary: Delete Subscription Plan
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Subscription plan successfully deleted

  # API Test
  /test:
    get:
      tags: ['API Test']
      summary: API Test Endpoint
      parameters:
        - $ref: '#/components/parameters/x-access-token'
      responses:
        '200':
          description: API is working